# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{bounce-email}
  s.version = "0.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Agris Ameriks", "Pedro Visintin"]
  s.date = %q{2011-03-01}
  s.description = %q{fork of wakiki/bounce-email working with mail gem and ruby 1.9}
  s.email = %q{pedro.visintin@gmail.com}
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "Gemfile",
    "Gemfile.lock",
    "History.txt",
    "Manifest.txt",
    "PostInstall.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bounce-email.gemspec",
    "lib/bounce_email.rb",
    "script/console",
    "script/destroy",
    "script/generate",
    "test/bounces/malformed_bounce_01.txt",
    "test/bounces/tt_1234175799.txt",
    "test/bounces/tt_1234177688.txt",
    "test/bounces/tt_1234210655.txt",
    "test/bounces/tt_1234210666.txt",
    "test/bounces/tt_1234211024.txt",
    "test/bounces/tt_1234211357.txt",
    "test/bounces/tt_1234211929.txt",
    "test/bounces/tt_1234211931.txt",
    "test/bounces/tt_1234211932.txt",
    "test/bounces/tt_1234241664.txt",
    "test/bounces/tt_1234241665.txt",
    "test/bounces/tt_1234285532.txt",
    "test/bounces/tt_1234285668.txt",
    "test/bounces/tt_bounce_01.txt",
    "test/bounces/tt_bounce_02.txt",
    "test/bounces/tt_bounce_03.txt",
    "test/bounces/tt_bounce_04.txt",
    "test/bounces/tt_bounce_05.txt",
    "test/bounces/tt_bounce_06.txt",
    "test/bounces/tt_bounce_07.txt",
    "test/bounces/tt_bounce_08.txt",
    "test/bounces/tt_bounce_09.txt",
    "test/bounces/tt_bounce_10.txt",
    "test/bounces/tt_bounce_11.txt",
    "test/bounces/tt_bounce_12_soft.txt",
    "test/bounces/tt_bounce_13.txt",
    "test/bounces/tt_bounce_14.txt",
    "test/bounces/tt_bounce_15.txt",
    "test/bounces/tt_bounce_16.txt",
    "test/bounces/tt_bounce_17.txt",
    "test/bounces/tt_bounce_18.txt",
    "test/bounces/tt_bounce_19.txt",
    "test/bounces/tt_bounce_20.txt",
    "test/bounces/tt_bounce_21.txt",
    "test/bounces/tt_bounce_22.txt",
    "test/bounces/tt_bounce_23.txt",
    "test/bounces/unknown_code_bounce_01.txt",
    "test/test_bounce_email.rb",
    "test/test_helper.rb"
  ]
  s.homepage = %q{http://github.com/peterpunk/bounce-email}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{detect kind of bounced email}
  s.test_files = [
    "test/test_bounce_email.rb",
    "test/test_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<mail>, [">= 0"])
    else
      s.add_dependency(%q<mail>, [">= 0"])
    end
  else
    s.add_dependency(%q<mail>, [">= 0"])
  end
end

